import { FloatingNav } from "@/components/layout/FloatingNav";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Geist_Mono, JetBrains_Mono } from "next/font/google";
import "./globals.css";

const jetbrainsMonoHeading = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-heading",
});

const geistMono = Geist_Mono({ subsets: ["latin"], variable: "--font-mono" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { PageTracker } from "@/components/PageTracker";
import { Toaster } from "@/components/ui/sonner";
export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={cn(
        "dark font-mono",
        geistMono.variable,
        jetbrainsMonoHeading.variable,
      )}
    >
      <body className="min-h-screen bg-background font-mono antialiased flex flex-col">
        <main className="flex-1">{children}</main>
        <FloatingNav />
        <Toaster />
        <PageTracker />
      </body>
    </html>
  );
}
