import type { Metadata } from "next";
import "./globals.css";
import { Geist_Mono, JetBrains_Mono } from "next/font/google";
import { cn } from "@/lib/utils";

const jetbrainsMonoHeading = JetBrains_Mono({subsets:['latin'],variable:'--font-heading'});

const geistMono = Geist_Mono({subsets:['latin'],variable:'--font-mono'});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={cn("font-mono", geistMono.variable, jetbrainsMonoHeading.variable)}>
      <body>{children}</body>
    </html>
  );
}
